[package]
name = "appelg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flagset = "0.4.4"
reduce = "0.1.5"
